name: Build Android Kernel

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-kernel:
    runs-on: ubuntu-latest

    steps:
    - name: Clone Kernel Source
      run: |
        git clone --depth=1 -b master https://github.com/Ridhoardhiansyah7/realme_C11-2021_Narzo-50i-AndroidR-kernel-source kernel_source
        ls -l kernel_source

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential bc bison flex libssl-dev libelf-dev ccache clang python3

    - name: Prepare Output Directory
      run: mkdir -p out

    - name: Generate Defconfig
      run: |
        make O=out ARCH=arm64 -C kernel_source sprd_sharkl3_defconfig

    - name: Build Kernel
      run: |
        make -j$(nproc) O=out ARCH=arm64 -C kernel_source \
          CC=clang \
          CROSS_COMPILE=aarch64-linux-gnu- \
          LLVM=1 \
          LLVM_IAS=1

    - name: Upload Kernel Image
      uses: actions/upload-artifact@v4
      with:
        name: Image.gz-dtb
        path: out/arch/arm64/boot/Image.gz-dtb
