name: Build Android Kernel

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-kernel:
    runs-on: ubuntu-latest

    steps:
    - name: Clone Kernel Source
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential bc bison flex libssl-dev libelf-dev ccache wget git python3

    - name: Setup LLVM Clang 17.0.7
      run: |
        wget https://github.com/llvm/llvm-project/releases/download/llvmorg-17.0.7/clang+llvm-17.0.7-x86_64-linux-gnu-ubuntu-20.04.tar.xz
        tar -xf clang+llvm-17.0.7-x86_64-linux-gnu-ubuntu-20.04.tar.xz
        echo "CLANG_PATH=$(pwd)/clang+llvm-17.0.7-x86_64-linux-gnu-ubuntu-20.04/bin" >> $GITHUB_ENV

    - name: Make Output Directory
      run: mkdir -p out

    - name: Generate Defconfig
      run: |
        make O=out ARCH=arm64 sprd_sharkl3_defconfig

    - name: Build Kernel
      run: |
        PATH=${{ env.CLANG_PATH }}:$PATH \
        make -j$(nproc) \
          O=out \
          ARCH=arm64 \
          CC=clang \
          CROSS_COMPILE=aarch64-linux-gnu- \
          LLVM=1 \
          LLVM_IAS=1

    - name: Upload Kernel Image
      uses: actions/upload-artifact@v4
      with:
        name: Image.gz-dtb
        path: out/arch/arm64/boot/Image.gz-dtb
